### PR TITLE
Content inputs to be processed according to the query.

### PR DESCRIPTION
**Pull request by thiago-aixplain**
```python
from aixplain.enums import Function, Supplier

from aixplain.factories import AgentFactory
from aixplain.modules.agent import ModelTool, PipelineTool

agent = AgentFactory.create(
    name="Test Agent 23423",
    tools=[
        ModelTool(
            function=Function.SPEECH_RECOGNITION,
            supplier=Supplier.MICROSOFT,
        ),
        ModelTool(
            function=Function.TRANSLATION,
            supplier=Supplier.MICROSOFT
        )
    ],
    description="Test Agent Description",
    supplier="aiXplain",
    version="1.0.0",
    # api_key="776baec37164e833039d030a5e48edc735e6cd038f04fa9642d39936e570905d",
    llm_id="6646261c6eb563165658bbb1",
)

response = agent.run(
    query="Translate the English texts within the links to Portuguese:",
    content_inputs=[
        "https://aixplain-platform-assets.s3.amazonaws.com/samples/en/CPAC1x2.txt",
        "https://aixplain-platform-assets.s3.amazonaws.com/samples/en/bestofyou.txt"
    ]
)
```

### CODE REVIEW

**Comment by tim-nelson** [comment]
1. Looks good except I think `files` would be clearer than `content_inputs`. Thoughts?
2. Does the user need to specify "within the links", or could it be possible to just say "Translate the English texts to Portuguese"?

**Comment by thiago-aixplain** [comment]
> 1. Looks good except I think `files` would be clearer than `content_inputs`. Thoughts?

The idea is that the user could set a text, url or file. Any other idea of name?

> 2. Does the user need to specify "within the links", or could it be possible to just say "Translate the English texts to Portuguese"?

I did not get this question. Can you please explain?

**Comment by tim-nelson** [comment]
**1. My question rephrased**
In your example, you write
`"query": "Translate the English texts within the links to Portuguese."`
Would the query still work if you only wrote
`"query": "Translate the English texts to Portuguese."`?
Would the Agent know where to get the text?


**2. Additional content name**
Ah, then how about we keep to just `content`. I don't think we need `_inputs` on the end, given we don't use that convention elsewhere. E.g. we write `data` and not `data_inputs`.

**3. Using the `data` parameter**
Have you considered using `data`? It may be overly complicated, but to be consistent with Models and Pipelines we'd include `query`, `content` and (maybe) `session_id` in a data parameter. (See the examples below.) Maybe there's a middle ground? I can see a use for `data` if users can include custom parameters that would be additional key-value pairs in the `data` dictionary:
- Session IDs for the other agents acting as tools to their 'main' agent?
- Changing configurations for some of the tools the agent uses? (Suppose we have a speech synthesis model that takes `voice` as an argument and we want to pass `John-MALE` in one case and a `Jane-Female` in another.)

What do you think?

**MODELS**
_1. Pass single input._
```
model.run("Tell me a joke about dogs.")

model.run(data={
    "text": "Tell me a joke about dogs."
})
```
_2. Pass multiple inputs._
```
model.run(
    {
        "text": "Tell me a joke about dogs.",
        "max_tokens": 10,
        "temperature": 0.5,
    }
)
```


**AGENTS**
_1. Pass single input._
```
agent.run("What is the name of the driver who won the Formula One Championship in 2023? Answer in an English audio.")

agent.run(data={
    "query": "What is the name of the driver who won the Formula One Championship in 2023? Answer in an English audio."
})
```

_2. Pass multiple inputs._
```
agent.run(data={
    "query": "Translate the English texts to Portuguese.",
    "content": [
        "This is a text string to translate.",
        "https://aixplain-platform-assets.s3.amazonaws.com/samples/en/CPAC1x2.txt",
        "/path/to/local/file.txt"
    ],
    "session_id": "2e275c1c-eb11-424a-824a-e0ae12c4b42d"
})
```

**Comment by thiago-aixplain** [comment]
> **1. My question rephrased** In your example, you write `"query": "Translate the English texts within the links to Portuguese."` Would the query still work if you only wrote `"query": "Translate the English texts to Portuguese."`? Would the Agent know where to get the text?

Yes, it would know where to get the text in both instructions
> 
> **2. Additional content name** Ah, then how about we keep to just `content`. I don't think we need `_inputs` on the end, given we don't use that convention elsewhere. E.g. we write `data` and not `data_inputs`.
> 
Nice. I will do the change accordingly.

> **3. Using the `data` parameter** Have you considered using `data`? It may be overly complicated, but to be consistent with Models and Pipelines we'd include `query`, `content` and (maybe) `session_id` in a data parameter. (See the examples below.) Maybe there's a middle ground? I can see a use for `data` if users can include custom parameters that would be additional key-value pairs in the `data` dictionary:
> 
> * Session IDs for the other agents acting as tools to their 'main' agent?
> * Changing configurations for some of the tools the agent uses? (Suppose we have a speech synthesis model that takes `voice` as an argument and we want to pass `John-MALE` in one case and a `Jane-Female` in another.)
> 
> What do you think?
> 
> **MODELS** _1. Pass single input._
> 
> ```
> model.run("Tell me a joke about dogs.")
> 
> model.run(data={
>     "text": "Tell me a joke about dogs."
> })
> ```
> 
> _2. Pass multiple inputs._
> 
> ```
> model.run(
>     {
>         "text": "Tell me a joke about dogs.",
>         "max_tokens": 10,
>         "temperature": 0.5,
>     }
> )
> ```
> 
> **AGENTS** _1. Pass single input._
> 
> ```
> agent.run("What is the name of the driver who won the Formula One Championship in 2023? Answer in an English audio.")
> 
> agent.run(data={
>     "query": "What is the name of the driver who won the Formula One Championship in 2023? Answer in an English audio."
> })
> ```
> 
> _2. Pass multiple inputs._
> 
> ```
> agent.run(data={
>     "query": "Translate the English texts to Portuguese.",
>     "content": [
>         "This is a text string to translate.",
>         "https://aixplain-platform-assets.s3.amazonaws.com/samples/en/CPAC1x2.txt",
>         "/path/to/local/file.txt"
>     ],
>     "session_id": "2e275c1c-eb11-424a-824a-e0ae12c4b42d"
> })
> ```

All right. I can also add a data field to be consistent with models and pipelines. The changes will be available by the end of the day.

**Review by tim-nelson — APPROVED** [review]

**Pull request merged**
